### ISSUE TITLE
Namsor SDK not in Maven repository

### ISSUE THREAD

**Issue by bspammer** [namsor/namsor-java-sdk2#2]
Hi, adding the maven dependency to my project fails.

Searching manually on https://mvnrepository.com, I can't see the artifact uploaded anywhere. Could this be added?

**Comment by namsor** [comment]
Hi Charlie,

Let me check what the process is to get indexed in the central repository. 

Meanwhile you can install locally using :
git clone https://github.com/namsor/namsor-java-sdk2
cd namsor-java-sdk2
mvn clean install

Then you can add the following to your POM.xml dependencies :
        <dependency>
            <groupId>com.namsor</groupId>
            <artifactId>namsor-sdk2</artifactId>
            <version>2.0.7</version>
        </dependency>

Best,
Elian

**Comment by namsor** [comment]
Request was made,
https://issues.sonatype.org/browse/OSSRH-53370

**Comment by namsor** [comment]
Request was accepted by Sonatype,
https://issues.sonatype.org/browse/OSSRH-53370

GPG Signature was created and submited to public servers, but there is still an issue with the build process. 

mvn clean package gpg:sign 
creates valid signature but 
mvn clean package gpg:sign deploy
creates invalid signature, so the packages are rejected by Sonatype.

**Comment by namsor** [comment]
Signed jars now in Central Maven Repository 
https://repo1.maven.org/maven2/com/namsor/namsor-sdk2/2.0.7/

**Comment by bspammer** [comment]
Thanks for the quick resopnse on this!
